apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-exports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.exportStorageSize }}
  storageClassName: standard-rwo
